version: '3.1'

services:
  bd:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=
      - DB_NAME=
      - DB_USER=
      - DB_PASS=
    ports:
      - "8000:8000"
    depends_on:
      - bd